DEPLOY:
  CONFIRM-BEGIN: true
  DEPLOY-STAGING: true
  DEPLOY-PRODUCTION: true
  CONFIRM-DEPLOY-PRODUCTION: true
  CONFIRM-SWITCH-TRAFFIC: true
  CONFIRMER: "jylipoti"
SWITCH-TRAFFIC:
  CONFIRM-BEGIN: true
STATUS:
  CONFIRM-BEGIN: false
DECOMMISSION:
  CONFIRM-BEGIN: true
