DEPLOY:
  CONFIRM_BEGIN: false
  DEPLOY_STAGING: true
  DEPLOY_PRODUCTION: true
  CONFIRM_DEPLOY_PRODUCTION: true
  CONFIRM_SWITCH_TRAFFIC: true
  CONFIRMER: "jylipoti"
  CLOUDFORMATION_DEPLOY: true
SWITCH-TRAFFIC:
  CONFIRM_SWITCH_TRAFFIC: true
STATUS:
  PLACEHOLDER: 'foo'
DECOMMISSION:
  PLACEHOLDER: 'foo'
