DEPLOY:
  CONFIRM_BEGIN: true
  DEPLOY_STAGING: true
  DEPLOY_PRODUCTION: true
  CONFIRM_DEPLOY_PRODUCTION: true
  CONFIRM_SWITCH_TRAFFIC: true
  CONFIRMER: "jylipoti"
  CLOUDFORMATION_DEPLOY: true
SWITCH_TRAFFIC:
  CONFIRM_BEGIN: true
STATUS:
  CONFIRM_BEGIN: false
DECOMMISSION:
  CONFIRM_BEGIN: true
